"""empty message

Revision ID: c62f70db2882
Revises: 
Create Date: 2022-08-23 17:50:42.377593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62f70db2882'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyecto',
    sa.Column('idproyecto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idproyecto'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('emailuser', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idusuario'),
    sa.UniqueConstraint('emailuser')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('proyecto')
    # ### end Alembic commands ###
